api_platform:
    title: OS2Display Service API
    description: 'API description'

    enable_re_doc: false
    enable_entrypoint: false

    defaults:
        route_prefix: 'v2'
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 30
        pagination_client_items_per_page: true

    formats:
        jsonld: ['application/ld+json']
        html: ['text/html']
        mime_types: ['multipart/form-data']

    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage

    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'

    path_segment_name_generator: api_platform.path_segment_name_generator.dash

    show_webby: false

    version: 1.0

    graphql:
        enabled: false
        graphiql:
            enabled: false

    doctrine:
        enabled: true

    swagger:
        versions: [3]
    #        api_keys:
    #            Do not set security scheme here!
    #            Set it in App\OpenApi\OpenApiFactory

    openapi:
        contact:
            name: ITKDev
            email: itkdev@mkb.aarhus.dk
        license:
            name: MIT
