gesdinet_jwt_refresh_token:
    path: /v2/authentication/token/refresh

authentication-token:
    path: /v2/authentication/token
    methods: ['POST']

authentication-screen:
    path: /v2/authentication/screen
    methods: ['POST']
    controller: App\Controller\Api\AuthScreenController

authentication-bind-screen:
    path: /v2/screens/{id}/bind
    methods: ['POST']
    controller: App\Controller\Api\AuthScreenBindController

authentication-unbind-screen:
    path: /v2/screens/{id}/unbind
    methods: ['POST']
    controller: App\Controller\Api\AuthScreenUnbindController

admin:
    path: /admin{subroutes}
    requirements:
        # https://symfony.com/doc/current/routing.html#slash-characters-in-route-parameters
        subroutes: '.*'
    methods: ['GET']
    controller: App\Controller\Admin\AdminController

client:
    path: /client{subroutes}
    requirements:
        # https://symfony.com/doc/current/routing.html#slash-characters-in-route-parameters
        subroutes: '.*'
    methods: ['GET']
    controller: App\Controller\Client\ClientController

when@dev:
    templates:
        path: /template{subroutes}
        methods: ['GET']
        requirements:
            # https://symfony.com/doc/current/routing.html#slash-characters-in-route-parameters
            subroutes: '.*'
        controller: App\Controller\Template\TemplateController

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin'
        subroutes: ''
