---
resources:
  App\Entity\User:
    attributes:
      security: 'is_granted("ROLE_ADMIN") or is_granted("ROLE_EXTERNAL_USER_ADMIN")'
      input: App\Dto\ExternalUserInput
      output: App\Dto\ExternalUserOutput
    itemOperations:
      get:
        path: '/external-users/{id}'
        openapi_context:
          description: Retrieves an External User resource.
          summary: Retrieve an External User resource.
          operationId: get-v1-external-user-id
          tags:
            - External Users
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

      put:
        path: '/external-users/{id}'
        openapi_context:
          description: Update an External User resource.
          summary: Update an External User resource.
          operationId: put-v1-external-user-id
          tags:
            - External Users
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        path: '/external-users/{id}'
        openapi_context:
          description: Delete an External User resource.
          summary: Delete an External User resource.
          operationId: delete-v1-external-user-id
          tags:
            - External Users
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

    collectionOperations:
      get:
        path: '/external-users'
        filters: ['entity.search_filter', 'entity.blameable_filter', 'entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter']
        openapi_context:
          operationId: get-v1-external-users
          description:  Retrieve a collection of External User resources.
          summary:  Retrieve a collection of External User resources.
          tags:
            - External Users
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

      post:
        path: '/external-users'
        openapi_context:
          operationId: create-v1-external-users
          description: Creates an External User resource.
          summary: Creates an External User resource.
          tags:
            - External Users
