---
resources:
  App\Entity\Tenant\PlaylistScreenRegion:
    security: 'is_granted("ROLE_SCREEN") or is_granted("ROLE_ADMIN")'
    output: App\Dto\PlaylistScreenRegion

    operations:
      ApiPlatform\Metadata\Get:
          # It needs to be here to generate ids in the collection lists.
          uriTemplate: '/playlist-screen-regions/{id}'
          controller: App\Controller\NotFoundAction
          openapiContext:
              # For backward compatibility
              operationId: getPlaylistScreenRegionItem

      ApiPlatform\Metadata\Delete:
        security: 'is_granted("ROLE_ADMIN")'
        uriTemplate: '/screens/{id}/regions/{regionId}/playlists/{playlistId}'
        controller: App\Controller\PlaylistScreenRegionDeleteController
        read: false
        deserialize: false
        validate: false
        openapiContext:
          # For backward compatibility
          operationId: deletePlaylistScreenRegionItem
          description: Remove Playlist resource from screen region.
          summary: Remove Playlist resource from screen region.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true

      ApiPlatform\Metadata\Put:
        security: 'is_granted("ROLE_ADMIN")'
        uriTemplate: '/screens/{id}/regions/{regionId}/playlists'
        controller: App\Controller\PlaylistScreenRegionPutController
        read: false
        deserialize: false
        validate: false
        openapiContext:
          # For backward compatibility
          operationId: putPlaylistScreenRegionItem
          description: Add Playlist resource from screen region.
          summary: Add Playlist resource from screen region.
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      playlist:
                        type: string
                        format: ulid
                        pattern: "^[A-Za-z0-9]{26}$"
                        description: Playlist ULID
                      weight:
                        type: integer
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
          responses:
            200:
              description: Not used - remove the default 200 response
            201:
              description: 'Created'
            404:
              description: 'Not found'

      ApiPlatform\Metadata\GetCollection:
        provider: App\State\PlaylistScreenRegionProvider
        filters: ['App\Filter\SharedWithMe']
        uriTemplate: '/screens/{id}/regions/{regionId}/playlists'
        openapiContext:
          operationId: get-v1-playlist-screen-regions
          description: Retrieve a Playlist resources base on screen regions.
          summary: Retrieves a Playlist resources base on screen region.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
