---
resources:
  App\Entity\PlaylistScreenRegion:
    itemOperations:
      delete:
        path: /screens/{id}/regions/{regionId}/playlists/{playlistId}
        controller: App\Controller\PlaylistScreenRegionDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true

      put:
        path: /screens/{id}/regions/{regionId}/playlists/{playlistId}
        controller: App\Controller\PlaylistScreenRegionPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: object
                  properties: { }
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true
          responses:
            200:
              description: Not used - remove the default 200 response
            201:
              description: 'Created'
            404:
              description: 'Not found'
    collectionOperations:
      get:
        controller: App\Controller\NotFoundAction
