---
resources:
  App\Entity\PlaylistScreenRegion:
    attributes:
      output: App\Dto\PlaylistScreenRegion
    itemOperations:
      get:
        # It needs to be here to generate id's in the collection lists.
        path: '/playlistScreenRegion/{id}'
        controller: App\Controller\NotFoundAction

      delete:
        path: /screens/{id}/regions/{regionId}/playlists/{playlistId}
        controller: App\Controller\PlaylistScreenRegionDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Remove Playlist resource from screen region.
          summary: Remove Playlist resource from screen region.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true

      put:
        path: /screens/{id}/regions/{regionId}/playlists/{playlistId}
        controller: App\Controller\PlaylistScreenRegionPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Add Playlist resource from screen region.
          summary: Add Playlist resource from screen region.
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: object
                  properties: { }
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true
          responses:
            200:
              description: Not used - remove the default 200 response
            201:
              description: 'Created'
            404:
              description: 'Not found'

    collectionOperations:
      get:
        path: /screens/{id}/regions/{regionId}/playlists
        controller: App\Controller\PlaylistScreenRegionGetController
        read: false
        openapi_context:
          operationId: get-v1-playlist-screen-regions
          description: Retrieve a Playlist resources base on screen regions.
          summary: Retrieves a Playlist resources base on screen region.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionId
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
