---
on:
  push:
    tags:
      - '*'
name: Build docker image (tag)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: itkdev/os2display-admin-client

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/display-api-service/
          file: ./infrastructure/display-api-service/Dockerfile
          build-args: |
            APP_VERSION=${{ env.GITHUB_REF_NAME }}
          push: true
          tags: itkdev/os2display-api-service:${{ env.GITHUB_REF_NAME }}

      - name: Build and push (Nginx)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/nginx/
          file: ./infrastructure/nginx/Dockerfile
          build-args: |
            VERSION=${{ env.GITHUB_REF_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
