---
on:
  push:
    branches:
      - 'develop'
name: Build docker image (develop)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION: alpha
      APP_VERSION: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build api
      - name: Docker meta (API)
        id: meta-api
        uses: docker/metadata-action@v3
        with:
          images: itkdev/os2display-api-service

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/display-api-service/
          file: ./infrastructure/display-api-service/Dockerfile
          build-args: |
            APP_VERSION=${{ github.ref }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build nginx (depends on api build)
      - name: Docker meta (Nginx)
        id: meta-nginx
        uses: docker/metadata-action@v3
        with:
          images: itkdev/os2display-api-service-nginx

      - name: Build and push (Nginx)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/nginx/
          file: ./infrastructure/nginx/Dockerfile
          build-args: |
            VERSION=${{ github.ref }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
